#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://UjjawalFirst:Mumma%401234@cluster0.8vbmwse.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: journaldb
#      auto-index-creation: true
#
#server:
#  port: 8080
#  servlet:
#    context-path: /journal

spring:
  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: mr.uj1508@gmail.com
    password: iply syjt gkdw ehwy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: d9126e67ec4895fae27fdd3c948e7a02

weather_api_key: d9126e67ec4895fae27fdd3c948e7a02